# Generated by Django 6.0 on 2025-12-25 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Villa Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('max_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Guests')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price Per Night (INR)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='villas/', verbose_name='Villa Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Amenities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Villa',
                'verbose_name_plural': 'Villas',
                'ordering': ['name'],
            },
        ),
    ]
