# Generated by Django 4.2.7 on 2026-01-08 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Weekend Days (0=Mon, 6=Sun)'),
        ),
        migrations.AddField(
            model_name='villa',
            name='weekend_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weekend Price (INR)'),
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='villas.villa')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('villa', 'date')},
            },
        ),
    ]
