# Generated by Django 4.2.7 on 2026-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_villa_weekend_days_villa_weekend_price_specialprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='special_prices',
            field=models.JSONField(blank=True, default=list, help_text='List of special pricing rules (ranges or specific dates)', verbose_name='Special Prices Config'),
        ),
        migrations.DeleteModel(
            name='SpecialPrice',
        ),
    ]
