# Generated by Django 4.2.7 on 2026-01-08 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0004_globalspecialday'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='special_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Special Day Price (INR)'),
        ),
    ]
