# Generated by Django 4.2.7 on 2026-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0005_villa_special_day_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villa',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Villa', 'verbose_name_plural': 'Villas'},
        ),
        migrations.AddField(
            model_name='villa',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
    ]
