"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import os
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-wkq+edhu9jxe#c1&)2t(($wvn)^m+u901gua3-9!7vwb45*6x4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)


ALLOWED_HOSTS = [
    "vacationbna.ai",
    "www.vacationbna.ai",
    "api.vacationbna.ai",
    "villa-backend-management-production.up.railway.app",
    ".railway.app",
    "localhost",
    "127.0.0.1",
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    
    # Local apps
    'accounts',
    'villas',
    'bookings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
import sys

# Initialize DATABASES dictionary
DATABASES = {}

# Check for DATABASE_URL in environment (for Railway/Production)
DATABASE_URL = config('DATABASE_URL', default=None)

# Check if we should use local PostgreSQL (only in DEBUG mode)
USE_LOCAL_DB = config('USE_LOCAL_DB', default=False, cast=bool)

if DATABASE_URL and not USE_LOCAL_DB:
    # Production / Railway usage (DATABASE_URL set and not forcing local DB)
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL)
    print("🚀 Using configured DATABASE_URL (PostgreSQL - Railway/Production)", file=sys.stderr)
elif USE_LOCAL_DB or (DEBUG and not DATABASE_URL):
    # Local development PostgreSQL
    # Database name can have spaces (e.g., "villa manage") - Django handles this automatically
    local_db_name = config('LOCAL_DB_NAME', default='villa_manage')
    local_db_user = config('LOCAL_DB_USER', default='postgres')
    local_db_password = config('LOCAL_DB_PASSWORD', default='adnan12')
    local_db_host = config('LOCAL_DB_HOST', default='localhost')
    local_db_port = config('LOCAL_DB_PORT', default='5432')
    
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': local_db_name,
        'USER': local_db_user,
        'PASSWORD': local_db_password,
        'HOST': local_db_host,
        'PORT': local_db_port,
    }
    print(f"🔧 Using local PostgreSQL database: {local_db_name} on {local_db_host}:{local_db_port}", file=sys.stderr)
else:
    # No DATABASE_URL found and not in DEBUG mode
    if not DEBUG:
        # CRITICAL: Fail in production if no DB URL is found (prevents data loss)
        print("❌ CRITICAL ERROR: DATABASE_URL is missing in production!", file=sys.stderr)
        print("   The application is refusing to start to prevent falling back to ephemeral SQLite.", file=sys.stderr)
        sys.exit(1)
    
    # Fallback to SQLite only as last resort
    print("⚠️  DATABASE_URL not found and local DB not configured, falling back to local SQLite", file=sys.stderr)
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT settings
# Read token lifetimes from environment variables (in minutes) or use defaults
# Default: 7 days (10080 minutes) for access token, 14 days (20160 minutes) for refresh token
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = config('JWT_ACCESS_TOKEN_LIFETIME', default=10080, cast=int)  # 7 days in minutes
JWT_REFRESH_TOKEN_LIFETIME_MINUTES = config('JWT_REFRESH_TOKEN_LIFETIME', default=20160, cast=int)  # 14 days in minutes

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=JWT_ACCESS_TOKEN_LIFETIME_MINUTES),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=JWT_REFRESH_TOKEN_LIFETIME_MINUTES),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ===== CORS (STRICT PRODUCTION) =====
# ===== CORS (STRICT PRODUCTION) =====
CORS_ALLOWED_ORIGINS = [
    "https://vacationbna.ai",
    "https://www.vacationbna.ai",
    "https://api.vacationbna.ai",
    "https://villa-backend-management-production.up.railway.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "content-type",
]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "https://vacationbna.ai",
    "https://www.vacationbna.ai",
    "https://api.vacationbna.ai",
    "https://villa-backend-management-production.up.railway.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Security settings for production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Villa Manager Hub API',
    'DESCRIPTION': 'API for managing villa bookings and reservations',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}


# Email Configuration
# Default to Console Backend for development/testing (prints to terminal)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
# For production, we will use 'django.core.mail.backends.smtp.EmailBackend'

# SMPT Settings (Load from environment or use placeholders)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='info@vacationbna.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Default From Email
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
