# Generated by Django 6.0 on 2025-12-25 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Client Phone')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Client Email')),
                ('check_in', models.DateField(verbose_name='Check-in Date')),
                ('check_out', models.DateField(verbose_name='Check-out Date')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('blocked', 'Blocked')], default='booked', max_length=20, verbose_name='Status')),
                ('number_of_guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Guests')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('advance', 'Advance Paid'), ('full', 'Fully Paid')], max_length=20, null=True, verbose_name='Payment Status')),
                ('booking_source', models.CharField(blank=True, choices=[('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('other', 'Other')], max_length=20, null=True, verbose_name='Booking Source')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount (INR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='villas.villa', verbose_name='Villa')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['villa', 'check_in', 'check_out'], name='bookings_bo_villa_i_996384_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
