# Generated by Django 4.2.7 on 2026-01-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Guests'),
        ),
    ]
