# Generated by Django 4.2.7 on 2026-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Amount paid in advance', max_digits=10, null=True, verbose_name='Advance Payment (INR)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated total booking amount', max_digits=10, null=True, verbose_name='Total Payment (INR)'),
        ),
    ]
