# Generated by Django 4.2.7 on 2026-01-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_total_amount_booking_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
