# Generated by Django 4.2.7 on 2026-01-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='override_total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override for total payment. If set, ignores auto-calculation.', max_digits=10, null=True, verbose_name='Override Total Payment (INR)'),
        ),
    ]
